### ISSUE TITLE
Can I use depthLimit()?

### ISSUE THREAD

**Issue by HeinKoZin** [nevadskiy/laravel-tree#31]
I want to get descendants limit with 5 depth from current user.

**Comment by HeinKoZin** [comment]
Thanks, mate! It worked!

**Comment by HeinKoZin** [comment]
Hello mate,

When I used 

`User::query()->whereSelfOrDescendantOf($auth)->withTrashed()->whereDepth(operator: '<=', depth: 20)->get()`

I got descendants list where depth 20 from root, not from current user.

How can I get whereDepth from current $auth user.

**Comment by nevadskiy** [comment]
Hi. Try calculating the current depth somehow and add this to the query depth. For example 
```
whereDepth(operator: '<=', depth: 20 + $auth->getPath()->getDepth())
```
