### ISSUE TITLE
Path is not being set.

### ISSUE THREAD

**Issue by rojermaharjan** [nevadskiy/laravel-tree#32]
I seeded in some user data and associated some users to others. User model has the trait implemented.
<code>
$currentUser->parent()->associate($currentManager);
$currentUser->save();
</code>

The path column in the database is NULL. When querying ancestors and descendants, I'm getting error saying getPath() must return a Path object and null is being returned.

Edit:
It was caused by WithoutModelEvents trait in the seeder class. Since, this package updates the path on created and creating events, they were not being set.

**Comment by nevadskiy** [comment]
Yes, you are correct, we need events to be on.
